# -*- coding: utf-8 -*-
"""maincraft Task 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o4E6SA6EIAMcH3V6rYaclSWtaC5_8jzp
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# display settings
pd.set_option('display.max_columns', None)
sns.set(style="whitegrid")

df = pd.read_excel("merged_student_data.xlsx")

# preview
df.head()

# shape of dataset
print("Dataset Shape:", df.shape)

# column info
df.info()

# statistical summary
df.describe()

# missing values
df.isnull().sum()

# duplicate rows
print("Duplicate rows:", df.duplicated().sum())

avg_math = df['G3_mat'].mean()
avg_port = df['G3_por'].mean()

print("Average Math Final Grade:", round(avg_math, 2))
print("Average Portuguese Final Grade:", round(avg_port, 2))

above_15_math = (df['G3_mat'] > 15).sum()
above_15_port = (df['G3_por'] > 15).sum()

print("Students scoring >15 in Math:", above_15_math)
print("Students scoring >15 in Portuguese:", above_15_port)

gender_avg = df.groupby('sex')[['G3_mat', 'G3_por']].mean()
gender_avg

# correlation
corr_math = df['studytime_mat'].corr(df['G3_mat'])
corr_port = df['studytime_por'].corr(df['G3_por'])

print("Study Time vs Math Grade Correlation:", round(corr_math, 2))
print("Study Time vs Portuguese Grade Correlation:", round(corr_port, 2))

plt.figure()
plt.hist(df['G3_mat'], bins=10)
plt.title("Distribution of Math Final Grades")
plt.xlabel("Grade")
plt.ylabel("Frequency")
plt.show()

plt.figure()
plt.hist(df['G3_por'], bins=10)
plt.title("Distribution of Portuguese Final Grades")
plt.xlabel("Grade")
plt.ylabel("Frequency")
plt.show()

gender_avg.plot(kind='bar')
plt.title("Gender-wise Average Final Grades")
plt.xlabel("Gender")
plt.ylabel("Average Grade")
plt.xticks(rotation=0)
plt.show()

plt.figure()
plt.scatter(df['studytime_mat'], df['G3_mat'])
plt.title("Study Time vs Math Final Grade")
plt.xlabel("Study Time")
plt.ylabel("Math Grade")
plt.show()

plt.figure()
plt.scatter(df['studytime_por'], df['G3_por'])
plt.title("Study Time vs Portuguese Final Grade")
plt.xlabel("Study Time")
plt.ylabel("Portuguese Grade")
plt.show()

"""🔟 Key Insights (Markdown for Notebook)
### Key Findings
- Average Math score is slightly different from Portuguese.
- More students score above 15 in Portuguese than Math.
- Study time shows a positive but moderate correlation with grades.
- Female students perform slightly better on average.
"""

